const makes: string[] = [
    "ABU",
    "Ace",
    "Acura",
    "Alfa Romeo",
    "AM General",
    "AMC",
    "American Motors",
    "Arctic Cat",
    "Aston Martin",
    "Audi",
    "Autocar",
    "Avanti",
    "Bentley",
    "Blue Bird",
    "BMW",
    "Boss Hoss",
    "Buck",
    "Bugatti",
    "Buick",
    "BWI",
    "Cadillac",
    "Campagna",
    "CAN-AM",
    "Carriage",
    "Caterpillar",
    "Chevrolet",
    "Chrysler",
    "Clenet",
    "Coachmen",
    "Coachworks",
    "Coleman",
    "Condor",
    "Country Coach",
    "Crosley",
    "Cruise Air",
    "Cushman",
    "Cutlass",
    "Daewoo",
    "Daihatsu",
    "Damon",
    "Datsun",
    "Diamond Cargo",
    "Ditch Witch",
    "Dodge",
    "DRV",
    "Ducati",
    "Eagle",
    "Elite",
    "Escape",
    "Essex Performance Boats",
    "Ferrari",
    "Fiat",
    "FLXIBLE",
    "Fontaine Trailer",
    "Ford",
    "Forest River",
    "Foretravel",
    "Four Winns",
    "Freightliner",
    "Galbreath",
    "Genesis",
    "Geo",
    "Glastron",
    "GMC",
    "Great Dane",
    "Grumman",
    "Harley Davidson",
    "Haulmark",
    "HEARTLAND",
    "Hino",
    "Holiday Rambler",
    "Honda",
    "Hummer",
    "Hymer",
    "Hyundai",
    "imperial",
    "Infiniti",
    "International",
    "Isuzu",
    "Jaguar",
    "Jayco",
    "Jeep",
    "JLG",
    "John Deere",
    "Kawasaki",
    "Kenworth",
    "Keystone",
    "Kia",
    "Koenigsegg",
    "Kruz",
    "KTM",
    "Kubota",
    "Lakota",
    "Lamborghini",
    "Lance",
    "Lancia",
    "Land Rover",
    "Lexus",
    "Lifestyle",
    "Lincoln",
    "Load Trail",
    "Lotus",
    "Mack",
    "MANAC",
    "Maserati",
    "Maybach",
    "Mazda",
    "McClain",
    "McLaren",
    "Mercedes-Benz",
    "Mercury",
    "MERKUR",
    "Miller",
    "MINI",
    "Mitsubishi",
    "Mitsubishi Fuso",
    "Monaco",
    "Monaco RV",
    "Monarch",
    "Morgan",
    "Moto Guzzi",
    "Nash",
    "Navistar",
    "Neoplan",
    "NEW HORIZONS",
    "Newell",
    "Nissan",
    "Oldsmobile",
    "Opel",
    "Oshkosh",
    "Outback",
    "Palomino",
    "Panoz",
    "Peterbilt",
    "Peugeot",
    "Phoenix",
    "Plymouth",
    "Polaris",
    "Pontiac",
    "Porsche",
    "Prevost",
    "Progress",
    "R-Vision",
    "Ram",
    "Ranger",
    "Renegade",
    "Roadmaster",
    "Rolls Royce",
    "SAAB",
    "Saleen",
    "Saturn",
    "Shasta",
    "Silver Streak",
    "Skyline",
    "Slingshot",
    "smart",
    "Spartan",
    "Sportscoach",
    "Spyker",
    "Starcraft",
    "Stealth",
    "Sterling Truck",
    "Subaru",
    "Sun Country",
    "Suzuki",
    "Talbert",
    "Tesla",
    "Thomas Built",
    "Toyota",
    "TRAILMANOR",
    "Triumph",
    "UD",
    "UTILITY",
    "Van Hool",
    "Vermeer",
    "Victory",
    "Volkswagen",
    "Volvo",
    "Volvo Truck",
    "Wally-Mo",
    "Western",
    "Western Star",
    "Winnebago",
    "Workhorse",
    "Yamaha",
    "YUGO",
    "Zimmer"
];

export default makes;